#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prompts_config.json 汉化脚本
自动为所有缺少中文名称的配置项添加中文翻译
"""

import json
import re
from pathlib import Path

# 完整的英文到中文翻译字典
TRANSLATION_DICT = {
    # negative_prompts 部分
    "lowres": "低分辨率",
    "bad anatomy": "解剖错误",
    "bad hands": "手部错误",
    "text": "文字",
    "error": "错误",
    "missing fingers": "缺少手指",
    "extra digit": "多余手指",
    "fewer digits": "手指过少",
    "cropped": "裁剪",
    "worst quality": "最差质量",
    "low quality": "低质量",
    "normal quality": "普通质量",
    "jpeg artifacts": "JPEG伪影",
    "signature": "签名",
    "watermark": "水印",
    "username": "用户名",
    "blurry": "模糊",
    
    # adult 部分
    "tentacle": "触手",
    "hairjob": "发丝服务",
    "oral/fellatio": "口交",
    "deepthroat": "深喉",
    "gokkun": "吞精",
    "gag": "口塞",
    "ballgag": "球塞",
    "bitgag": "咬塞",
    "ring_gag": "环塞",
    "cleave_gag": "布条塞",
    "panty_gag": "内裤塞",
    "tapegag": "胶带塞",
    "facial": "颜射",
    "leash": "项圈",
    "handjob": "手交",
    "groping": "抚摸",
    "areolae": "乳晕",
    "nipples": "乳头",
    "puffy_nipples": "肥大乳头",
    "small_nipples": "小乳头",
    "nipple_pull": "拉扯乳头",
    "nipple_torture": "乳头折磨",
    "nipple_tweak": "扭捏乳头",
    "nipple_piercing": "乳头穿孔",
    "breast_grab": "抓胸",
    "lactation": "泌乳",
    "breast_sucking/nipple_suck": "吸乳",
    "breast_feeding": "哺乳",
    "paizuri": "乳交",
    "multiple_paizuri": "多人乳交",
    "breast_smother": "乳压",
    "piercing": "穿孔",
    "navel_piercing": "肚脐穿孔",
    "thigh_sex": "腿交",
    "footjob": "足交",
    "mound_of_venus": "阴阜",
    "wide_hips": "宽臀",
    "masturbation": "自慰",
    "clothed_masturbation": "穿衣自慰",
    "penis": "阴茎",
    "testicles": "睾丸",
    "ejaculation": "射精",
    "cum": "精液",
    "cum_inside": "内射",
    "cum_on_breast": "胸射",
    "cum_on_hair": "发射",
    "cum_on_food": "食物射精",
    "tamakeri": "踢蛋",
    "pussy/vaginal": "阴道",
    "pubic_hair": "阴毛",
    "shaved_pussy": "剃毛",
    "no_pussy": "无阴道",
    "clitoris": "阴蒂",
    "fat_mons": "肥厚阴阜",
    "cameltoe": "骆驼趾",
    "pussy_juice": "爱液",
    "female_ejaculation": "女性射液",
    "grinding": "磨蹭",
    "crotch_rub": "胯部摩擦",
    "facesitting": "坐脸",
    "cervix": "子宫颈",
    "cunnilingus": "舔阴",
    "insertion": "插入",
    "anal_insertion": "肛插入",
    "fruit_insertion": "水果插入",
    "large_insertion": "大物体插入",
    "penetration": "贯穿",
    "fisting": "拳交",
    "fingering": "指交",
    "multiple_insertions": "多重插入",
    "double_penetration": "双穴",
    "triple_penetration": "三穴",
    "double_vaginal": "双阴道",
    "peeing": "排尿",
    "have_to_pee": "憋尿",
    "ass": "臀部",
    "huge_ass": "巨臀",
    "spread_ass": "掰臀",
    "buttjob": "臀交",
    "spanked": "打屁股",
    "anus": "肛门",
    "anal": "肛交",
    "double_anal": "双肛",
    "anal_fingering": "肛指交",
    "anal_fisting": "肛拳交",
    "anilingus": "舔肛",
    "enema": "灌肠",
    "stomach_bulge": "腹部隆起",
    "x-ray/cross-section/internal_cumshot": "透视/剖面/内射",
    "wakamezake": "海藻酒",
    "public": "公共场合",
    "humiliation": "羞辱",
    "bra_lift": "掀起胸罩",
    "panties_around_one_leg": "单腿内裤",
    "caught": "被抓",
    "walk-in": "闯入",
    "body_writing": "身体涂鸦",
    "tally": "计数",
    "futanari": "扶他",
    "incest": "乱伦",
    "twincest": "双胞胎乱伦",
    "pegging": "女对男肛交",
    "femdom": "女性支配",
    "ganguro": "黑辣妹",
    "bestiality": "兽交",
    "gangbang": "轮奸",
    "threesome": "三人行",
    "group_sex/orgy/teamwork": "群交/乱交/合作",
    "tribadism": "磨豆腐",
    "molestation": "骚扰",
    "voyeurism": "偷窥",
    "exhibitionism": "暴露癖",
    "rape": "强奸",
    "about_to_be_raped": "即将被强奸",
    "sex": "性交",
    "clothed_sex": "穿衣性交",
    "happy_sex": "愉悦性交",
    "underwater_sex": "水下性交",
    "spitroast": "烤肉串",
    "cock_in_thighhigh": "阴茎在大腿袜间",
    "69": "69式",
    "doggystyle": "后入式",
    "leg_lock/upright_straddle": "腿部锁定/直立跨坐",
    "missionary": "传教士体位",
    "girl_on_top": "女上位",
    "cowgirl_position": "骑乘位",
    "reverse_cowgirl": "反向骑乘",
    "virgin": "处女",
    "slave": "奴隶",
    "shibari": "日式绑缚",
    "bondage": "束缚",
    "bdsm": "调教",
    "pillory/stocks": "枷锁",
    "rope": "绳索",
    "bound_arms": "绑臂",
    "bound_wrists": "绑腕",
    "crotch_rope": "股绳",
    "hogtie": "猪绑",
    "frogtie": "蛙绑",
    "suspension": "悬吊",
    "spreader_bar": "腿撑杆",
    "wooden_horse": "木马",
    "anal_beads": "肛珠",
    "dildo": "假阳具",
    "cock_ring": "阴茎环",
    "egg_vibrator": "跳蛋",
    "artificial_vagina": "人造阴道",
    "hitachi_magic_wand": "日立魔杖",
    "double_dildo": "双头假阳具",
    "vibrator": "振动器",
    "vibrator_in_thighhighs": "大腿袜内振动器",
    "nyotaimori": "女体盛",
    "vore": "吞噬",
    "amputee": "截肢",
    "transformation": "变身",
    "mind_control": "精神控制",
    "censored": "打码",
    "uncensored": "无码",
    "asian": "亚洲人",
    "faceless_male": "无脸男",
    "blood": "血液",
    
    # expression 部分
    "eyes_closed": "闭眼",
    "wink": "眨眼",
    "blinking": "眨眼",
    "slit_pupils": "瞳孔裂缝",
    "heterochromia": "异色瞳",
    "heart-shaped_pupils": "心形瞳孔",
    "eyelid_pull": "拉眼皮",
    "aqua_eyes": "水色眼睛",
    "tsurime": "上翘眼",
    "eyeball": "眼球",
    "tears": "眼泪",
    "smelling": "闻",
    "nosebleed": "流鼻血",
    "lips": "嘴唇",
    "clenched_teeth": "咬紧牙关",
    "open_mouth": "张嘴",
    "pout": "嘟嘴",
    "sigh": "叹气",
    "smile": "微笑",
    "grin": "咧嘴笑",
    "stare": "凝视",
    "angry": "生气",
    "annoyed": "恼火",
    "crazy": "疯狂",
    "shy": "害羞",
    "embarrassed": "尴尬",
    "blush": "脸红",
    "sleepy": "困倦",
    "sad": "悲伤",
    "drunk": "醉酒",
    "dark_persona": "黑暗人格",
    "frown": "皱眉",
    "expressionless": "无表情",
    "rolleyes": "翻白眼",
    "ahegao": "阿黑颜",
    "fucked_silly": "傻笑",
    "naughty_face": "调皮表情",
    "endured_face": "忍耐表情",
    "looking_at_viewer": "直视观众",
    "gasping": "喘息",
    "slightly_open_mouth": "微张嘴",
    "wavy_mouth": "波浪嘴",
    "close_mouth": "闭嘴",
    "dot_mouth": "点嘴",
    "no_mouth": "无嘴",
    "gnaw": "啃咬",
    "parted_lips": "分开的嘴唇",
    "surprised": "惊讶",
    "bit_gag": "咬塞",
    "chestnut_mouth": "栗子嘴",
    "closed_mouth": "闭嘴",
    "covered_mouth": "捂嘴",
    "hair_in_mouth": "嘴里含发",
    "hair_tie_in_mouth": "嘴里含发带",
    "homu": "呆萌",
    "mouth": "嘴",
    "mouth_hold": "嘴里含物",
    "oral": "口交",
    "pacifier": "奶嘴",
    "puckered_lips": "嘟唇",
    "sideways_mouth": "歪嘴",
    "spoon_in_mouth": "嘴里含勺",
    "triangle_mouth": "三角嘴",
    "saliva": "唾液",
    "drooling": "流口水",
    "mouth_drool": "嘴边口水",
    "teeth": "牙齿",
    "upper_teeth": "上牙",
    "fang": "尖牙",
    "skin_fang": "皮肤尖牙",
    "round_teeth": "圆牙",
    "sharp_teeth": "尖牙",
    "buck_teeth": "龅牙",
    "fang_out": "露出尖牙",
    "fangs": "尖牙",
    "tooth": "牙齿",
    "toothbrush": "牙刷",
    "tusks": "獠牙",
    "shark_mouth": "鲨鱼嘴",
    "no_nose": "无鼻",
    "dot_nose": "点鼻",
    "nose_bubble": "鼻涕泡",
    "nose": "鼻子",
    "snot": "鼻涕",
    "snout": "口鼻部",
    "french_kiss": "法式接吻",
    "long_tongue": "长舌头",
    "oral_invitation": "口交邀请",
    "tongue": "舌头",
    "tongue_out": "吐舌头",
    "uvula": "悬雍垂",
    "kind_smile": "温柔微笑",
    "laughing": "大笑",
    "teasing_smile": "戏弄微笑",
    "seductive_smile": "诱惑微笑",
    "smirk": "坏笑",
    "giggling": "咯咯笑",
    "smug": "得意",
    "evil_smile": "邪恶微笑",
    "crazy_smile": "疯狂微笑",
    "happy": "开心",
    "happy_birthday": "生日快乐",
    "happy_halloween": "万圣节快乐",
    "happy_new_year": "新年快乐",
    "happy_tears": "喜极而泣",
    "happy_valentine": "情人节快乐",
    "tear": "眼泪",
    "crying": "哭泣",
    "streaming_tears": "泪流满面",
    "crying_with_eyes_open": "睁眼哭泣",
    "teardrop": "泪滴",
    "tearing_clothes": "撕衣服",
    "tearing_up": "含泪",
    "wiping_tears": "擦眼泪",
    "badmood": "心情不好",
    "unamused": "无趣",
    "frustrated": "沮丧",
    "frustrated_brow": "沮丧眉头",
    "anguish": "痛苦",
    "gloom": "忧郁",
    "disappointed": "失望",
    "despair": "绝望",
    "disgust": "厌恶",
    "disdain": "蔑视",
    "contempt": "轻蔑",
    "shaded_face": "阴影脸",
    "jitome": "死鱼眼",
    "wince": "畏缩",
    "furrowed_brow": "皱眉",
    "fear_kubrick": "恐惧凝视",
    "glaring": "怒视",
    "serious": "严肃",
    "kubrick_stare": "库布里克凝视",
    "evil": "邪恶",
    "sulking": "生闷气",
    "screaming": "尖叫",
    "shouting": "大喊",
    "bored": "无聊",
    "restrained": "克制",
    "confused": "困惑",
    "thinking": "思考",
    "lonely": "孤独",
    "exhausted": "疲惫",
    "determined": "坚定",
    "tsundere": "傲娇",
    "yandere": "病娇",
    "light_blush": "微红",
    "multiple_persona": "多重人格",
    "jekyll_and_hyde": "双重人格",
    "twitching": "抽搐",
    "spasm": "痉挛",
    "facepalm": "扶额",
    "rape_face": "强奸脸",
    "flustered": "慌张",
    "rolling_eyes": "翻白眼",
    "sweat": "汗水",
    "envy": "嫉妒",
    "scared": "害怕",
    "female_orgasm": "女性高潮",
    "heavy_breathing": "沉重呼吸",
    "moaning": "呻吟",
    "scowl": "怒容",
    
    # pose 部分
    "standing": "站立",
    "on_back": "仰卧",
    "on_stomach": "俯卧",
    "kneeling": "跪着",
    "on_side": "侧卧",
    "top-down_bottom_up": "俯视仰视",
    "on_pose": "摆姿势",
    "bent_over": "弯腰",
    "upside-down": "倒立",
    "reversal": "反转",
    "fighting_stance": "战斗姿势",
    "leaning_to_the_side": "侧倾",
    "leaning": "倾斜",
    "leaning_back": "后仰",
    "leaning_on_object": "靠物",
    "arched_back": "拱背",
    "leaning_forward": "前倾",
    "afloat": "漂浮",
    "lying": "躺下",
    "fetal_position": "胎儿姿势",
    "lying_on_person": "躺在人身上",
    "lying_on_the_lake": "躺在湖上",
    "lying_on_water": "躺在水上",
    "prone_bone": "俯卧",
    "reclining": "斜倚",
    "sleeping_upright": "直立睡觉",
    "presenting": "展示",
    "spinning": "旋转",
    "posing": "摆姿势",
    "stylish_pose": "时尚姿势",
    "public_indecency": "公共场合猥亵",
    "parody": "恶搞",
    "in_container": "在容器中",
    "against_glass": "贴着玻璃",
    "aiming": "瞄准",
    "aiming_at_viewer": "瞄准观众",
    "applying_makeup": "化妆",
    "bathing": "洗澡",
    "biting": "咬",
    "bleeding": "流血",
    "blowing": "吹",
    "bowing": "鞠躬",
    "breathing_fire": "喷火",
    "broom_riding": "骑扫帚",
    "brushing_teeth": "刷牙",
    "bubble_blowing": "吹泡泡",
    "bullying": "欺凌",
    "burning": "燃烧",
    "cast": "投掷",
    "chasing": "追逐",
    "cleaning": "清洁",
    "climbing": "攀爬",
    "comforting": "安慰",
    "cooking": "烹饪",
    "cuddling": "拥抱",
    "dancing": "跳舞",
    "diving": "潜水",
    "dragging": "拖拽",
    "drawing": "绘画",
    "drawing_bow": "拉弓",
    "dreaming": "做梦",
    "drinking": "喝水",
    "eating": "进食",
    "exercise": "运动",
    "fighting": "战斗",
    "firing": "开火",
    "fishing": "钓鱼",
    "flapping": "拍打",
    "flashing": "闪烁",
    "fleeing": "逃跑",
    "flexing": "弯曲",
    "flying": "飞行",
    "flying_kick": "飞踢",
    "hair_brushing": "梳头",
    "hanging": "悬挂",
    "hitting": "打击",
    "imagining": "想象",
    "jumping": "跳跃",
    "kicking": "踢",
    "licking": "舔",
    "licking_lips": "舔唇",
    "lip_biting": "咬唇",
    "meditation": "冥想",
    "painting": "绘画",
    "playing_card": "玩牌",
    "playing_games": "玩游戏",
    "playing_instrument": "演奏乐器",
    "pole_dancing": "钢管舞",
    "praying": "祈祷",
    "punching": "拳击",
    "pushing": "推",
    "railing": "栏杆",
    "reading": "阅读",
    "riding": "骑乘",
    "running": "跑步",
    "sewing": "缝纫",
    "shopping": "购物",
    "showering": "淋浴",
    "sing": "唱歌",
    "singing": "唱歌",
    "slashing": "挥砍",
    "sleeping": "睡觉",
    "smoking": "吸烟",
    "sneezing": "打喷嚏",
    "snowing": "下雪",
    "soaking_feet": "泡脚",
    "soccer": "足球",
    "spilling": "溢出",
    "spitting": "吐痰",
    "splashing": "溅水",
    "standing_on_liquid": "站在液体上",
    "standing_on_one_leg": "单腿站立",
    "standing_split": "站立劈叉",
    "steepled_fingers": "指尖相触",
    "strangling": "勒颈",
    "stretch": "伸展",
    "sweeping": "扫地",
    "swimming": "游泳",
    "swing": "荡秋千",
    "tail_wagging": "摇尾巴",
    "taking_picture": "拍照",
    "talking": "说话",
    "talking_on_phone": "打电话",
    "teasing": "戏弄",
    "tickling": "挠痒",
    "toilet_use": "使用厕所",
    "tossing": "抛掷",
    "tripping": "绊倒",
    "trolling": "恶作剧",
    "tying": "系",
    "unsheathing": "拔剑",
    "untying": "解开",
    "unzipping": "拉开拉链",
    "wading": "涉水",
    "waking_up": "醒来",
    "walking": "行走",
    "walking_on_liquid": "在液体上行走",
    "washing": "洗涤",
    "whispering": "耳语",
    "wrestling": "摔跤",
    "writing": "写作",
    "yawning": "打哈欠",
    "hiding": "躲藏",
    "arms_out_of_frame": "手臂在画框外",
    "feet_out_of_frame": "脚在画框外",
    "giving_up_the_ghost": "放弃灵魂",
    "glowing": "发光",
    "glowing_eye": "发光眼睛",
    "glowing_weapon": "发光武器",
    "hands_out_of_frame": "手在画框外",
    "out_of_frame": "在画框外",
    "paid": "付费",
    "upskirt": "裙底",
    "arms_behind_back": "双手背后",
    "arm_above_head": "手臂过头",
    "arm_behind_head": "手臂在头后",
    "crossed_arms": "交叉双臂",
    "arm_support": "手臂支撑",
    "armpits": "腋下",
    "arms_up": "举起双臂",
    "hand_on_hip": "手叉腰",
    "hands_on_hips": "双手叉腰",
    "arm_around_waist": "手臂搂腰",
    "caramelldansen": "焦糖舞",
    "hands_in_opposite_sleeves": "手在对侧袖子",
    "spread_arms": "张开双臂",
    "waving": "挥手",
    "outstretched_arms": "伸展双臂",
    "v_arms": "V形手臂",
    "w_arms": "W形手臂",
    "salute": "敬礼",
    "reaching": "伸手",
    "reaching_out": "伸出手",
    "hugging_own_legs": "抱自己的腿",
    "arm_blade": "手臂刀刃",
    "arm_grab": "抓手臂",
    "arm_held_back": "手臂被拉回",
    "arm_ribbon": "手臂丝带",
    "bandaged_arm": "包扎的手臂",
    "bandaid_on_arm": "手臂创可贴",
    "convenient_arm": "便利手臂",
    "extra_arms": "多臂",
    "locked_arms": "锁住的手臂",
    "arm_at_side": "手臂在身侧",
    "arm_behind_back": "手臂在背后",
    "shou_behind_head": "手在头后",
    "arm_cannon": "手臂炮",
    "arm_hug": "手臂拥抱",
    "arm_up": "举起手臂",
    "arms_at_sides": "双臂在身侧",
    "finger": "手指",
    "hand_to_mouth": "手捂嘴",
    "shushing": "嘘声",
    "cat_pose": "猫咪姿势",
    "claw_pose": "爪子姿势",
    "paw_pose": "爪子姿势",
    "fox_shadow_puppet": "狐狸手影",
    "double_fox_shadow_puppet": "双狐狸手影",
    "finger_gun": "手指枪",
    "v": "V手势",
    "double_v": "双V手势",
    "thumbs_up": "竖大拇指",
    "index_finger_raised": "举起食指",
    "middle_finger": "中指",
    "grimace": "做鬼脸",
    "fingersmile": "手指微笑",
    "finger_on_trigger": "手指在扳机上",
    "pointing_at_self": "指向自己",
    "pointing_at_viewer": "指向观众",
    "pointing_up": "指向上方",
    "poking": "戳",
    "hand_gesture": "手势",
    "ok_sign": "OK手势",
    "shading_eyes": "遮阳",
    "finger_biting": "咬手指",
    "finger_in_mouth": "手指在嘴里",
    "finger_sucking": "吸手指",
    "fingering_through_clothes": "隔着衣服指交",
    "fingers_together": "手指并拢",
    "hair_twirling": "卷发",
    "tease_one's_hair": "玩弄头发",
    "hands_clasped": "双手合十",
    "holding_hair": "抓头发",
    "pointing": "指向",
    "sharp_fingernails": "尖锐指甲",
    "sleeves_past_fingers": "袖子超过手指",
    "spread_fingers": "张开手指",
    "trigger_discipline": "扳机纪律",
    "w": "W手势",
    "balancing": "平衡",
    "curvy": "曲线",
    
    # 坐姿相关
    "sitting_on_xx": "坐在XX上",
    "butterfly_sitting": "蝴蝶坐",
    "lotus_position": "莲花坐",
    "sitting_on_railing": "坐在栏杆上",
    "sitting_on_rock": "坐在岩石上",
    "sitting_on_stairs": "坐在楼梯上",
    "sitting_on_table": "坐在桌子上",
    "sitting_on_water": "坐在水上",
    "cushion": "坐垫",
    "indian_style": "盘腿坐",
    "sitting_on_chair": "坐在椅子上",
    "sidesaddle": "侧骑",
    "sitting_on_bed": "坐在床上",
    "sitting_on_person": "坐在人身上",
    "upright_straddle": "直立跨坐",
    "squatting": "蹲着",
    "one_knee": "单膝跪地",
    "all_fours": "四肢着地",
    "gravure_pose": "写真姿势",
    "high_kick": "高踢腿",
    "bare_legs": "光腿",
    "between_legs": "腿间",
    "cropped_legs": "裁剪腿部",
    "kda_league_of_legends": "KDA英雄联盟",
    "leg_belt": "腿带",
    "leg_hair": "腿毛",
    "legs_apart": "分开双腿",
    "long_legs": "长腿",
    "lowleg": "低腰",
    "mechanical_legs": "机械腿",
    "multiple_legs": "多腿",
    "no_legs": "无腿",
    "no_legwear": "无腿饰",
    "tail_between_legs": "尾巴夹腿",
    "foot_out_of_frame": "脚在画框外",
    "footprints": "脚印",
    "dirty_feet": "脏脚",
    "feet": "脚",
    "feet_up": "抬起脚",
    "wrong_feet": "错误的脚",
    "pigeon_toed": "内八字",
    "tiptoes": "踮脚",
    "toe_point": "脚尖点地",
    "ankle_strap": "脚踝带",
    "ankle_wrap": "脚踝缠绕",
    "crossed_ankles": "交叉脚踝",
    "pince_nez": "夹鼻眼镜",
    "folded": "折叠",
    "thick_thighs": "粗大腿",
    "thigh_holster": "大腿枪套",
    "asymmetrical_docking": "不对称对接",
    "back_to_back": "背对背",
    "eye_contact": "眼神接触",
    "facing_another": "面向他人",
    "facing_away": "背对",
    "feeding": "喂食",
    "finger_in_another_mouth": "手指在他人嘴里",
    "giving": "给予",
    "hug": "拥抱",
    "imminent_kiss": "即将接吻",
    "incoming_food": " incoming食物",
    "incoming_gift": " incoming礼物",
    "incoming_kiss": " incoming接吻",
    "interlocked_fingers": "十指相扣",
    "kabedon": "壁咚",
    "lap_pillow": "膝枕",
    "mimikaki": "掏耳朵",
    "princess_carry": "公主抱",
    "shared_bathing": "共浴",
    "shared_food": "共享食物",
    "sitting_on_head": "坐在头上",
    "sitting_on_shoulder": "坐在肩上",
    "slapping": "拍打",
    "spanking": "打屁股",
    "special_feeling_meme": "特殊感觉梗",
    "symmetrical_docking": "对称对接",
    "ear_biting": "咬耳朵",
    "mixed_bathing": "混浴",
    
    # 其他常见标签
    "artist": "画师",
    "style": "风格",
    "quality": "质量",
    "scene": "场景",
    "pose": "姿势",
    "clothing": "服装",
    "lighting": "光线",
    "camera": "相机",
    "background": "背景",
    "character": "角色",
    "face": "脸",
    "body": "身体",
    "hair": "头发",
    "eyes": "眼睛",
    "mouth": "嘴巴",
    "nose": "鼻子",
    "ears": "耳朵",
    "hands": "手",
    "feet": "脚",
    "legs": "腿",
    "arms": "手臂",
    "breasts": "胸部",
    "butt": "臀部",
    "skin": "皮肤",
    "muscle": "肌肉",
    "fat": "脂肪",
    "thin": "瘦",
    "tall": "高",
    "short": "矮",
    "young": "年轻",
    "old": "年老",
    "beautiful": "美丽",
    "ugly": "丑陋",
    "cute": "可爱",
    "sexy": "性感",
    "elegant": "优雅",
    "cool": "酷",
    "funny": "有趣",
    "scary": "可怕",
    "sad": "悲伤",
    "happy": "快乐",
    "angry": "生气",
    "surprised": "惊讶",
    "confused": "困惑",
    "thinking": "思考",
    "sleeping": "睡觉",
    "eating": "吃东西",
    "drinking": "喝水",
    "running": "跑步",
    "walking": "走路",
    "jumping": "跳跃",
    "flying": "飞行",
    "swimming": "游泳",
    "dancing": "跳舞",
    "singing": "唱歌",
    "playing": "玩耍",
    "working": "工作",
    "studying": "学习",
    "reading": "阅读",
    "writing": "写作",
    "drawing": "绘画",
    "painting": "画画",
    "sculpting": "雕刻",
    "crafting": "手工艺",
    "cooking": "烹饪",
    "baking": "烘焙",
    "cleaning": "清洁",
    "gardening": "园艺",
    "farming": "农业",
    "hunting": "打猎",
    "fishing": "钓鱼",
    "camping": "露营",
    "hiking": "徒步",
    "climbing": "攀爬",
    "skiing": "滑雪",
    "snowboarding": "单板滑雪",
    "skating": "滑冰",
    "surfing": "冲浪",
    "diving": "潜水",
    "sailing": "帆船",
    "boating": "划船",
    "driving": "驾驶",
    "riding": "骑乘",
    "cycling": "骑自行车",
    "motorcycling": "骑摩托车",
    "flying": "飞行",
    "space": "太空",
    "underwater": "水下",
    "underground": "地下",
    "sky": "天空",
    "cloud": "云",
    "sun": "太阳",
    "moon": "月亮",
    "star": "星星",
    "rainbow": "彩虹",
    "rain": "雨",
    "snow": "雪",
    "wind": "风",
    "storm": "暴风雨",
    "thunder": "雷",
    "lightning": "闪电",
    "fog": "雾",
    "mist": "薄雾",
    "smoke": "烟",
    "fire": "火",
    "water": "水",
    "earth": "土",
    "air": "空气",
    "metal": "金属",
    "wood": "木头",
    "stone": "石头",
    "crystal": "水晶",
    "glass": "玻璃",
    "plastic": "塑料",
    "rubber": "橡胶",
    "leather": "皮革",
    "fabric": "织物",
    "paper": "纸",
    "cardboard": "纸板",
    "ceramic": "陶瓷",
    "porcelain": "瓷器",
    "ivory": "象牙",
    "bone": "骨头",
    "horn": "角",
    "shell": "贝壳",
    "feather": "羽毛",
    "fur": "毛皮",
    "wool": "羊毛",
    "silk": "丝绸",
    "cotton": "棉花",
    "linen": "亚麻",
    "velvet": "天鹅绒",
    "satin": "缎子",
    "lace": "蕾丝",
    "denim": "牛仔布",
    "leather": "皮革",
    "suede": "麂皮",
    "fur": "毛皮",
    "wool": "羊毛",
    "cashmere": "羊绒",
    "mohair": "马海毛",
    "angora": "安哥拉毛",
    "alpaca": "羊驼毛",
    "llama": "美洲驼毛",
    "vicuna": "小羊驼毛",
    "guanaco": "原驼毛",
    "camel": "骆驼毛",
    "yak": "牦牛毛",
    "bison": "野牛毛",
    "buffalo": "水牛毛",
    "muskox": "麝牛毛",
    "goat": "山羊毛",
    "sheep": "绵羊毛",
    "lamb": "羔羊毛",
    "kid": "小山羊毛",
    "mohair": "马海毛",
    "cashgora": "开司米安哥拉毛",
    "cashmere": "羊绒",
    "pashmina": "帕什米纳",
    "shahtoosh": "沙图什",
    "vicuna": "小羊驼毛",
    "guanaco": "原驼毛",
    "llama": "美洲驼毛",
    "alpaca": "羊驼毛",
    "camel": "骆驼毛",
    "yak": "牦牛毛",
    "bison": "野牛毛",
    "buffalo": "水牛毛",
    "muskox": "麝牛毛",
    "goat": "山羊毛",
    "sheep": "绵羊毛",
    "lamb": "羔羊毛",
    "kid": "小山羊毛",
}

def translate_name(name):
    """
    翻译英文名称为中文
    如果字典中有对应翻译则返回中文，否则返回None
    """
    # 直接查找
    if name in TRANSLATION_DICT:
        return TRANSLATION_DICT[name]
    
    # 尝试小写查找
    if name.lower() in TRANSLATION_DICT:
        return TRANSLATION_DICT[name.lower()]
    
    # 尝试替换下划线为空格查找
    name_with_space = name.replace('_', ' ')
    if name_with_space in TRANSLATION_DICT:
        return TRANSLATION_DICT[name_with_space]
    
    # 尝试替换空格为下划线查找
    name_with_underscore = name.replace(' ', '_')
    if name_with_underscore in TRANSLATION_DICT:
        return TRANSLATION_DICT[name_with_underscore]
    
    return None

def process_item(item):
    """
    处理单个配置项
    如果缺少中文名称，则尝试翻译并添加
    """
    if isinstance(item, dict):
        if 'name' in item and 'chinese' not in item:
            name = item['name']
            chinese = translate_name(name)
            if chinese:
                item['chinese'] = chinese
                print(f"已添加翻译: {name} -> {chinese}")
                return True
            else:
                print(f"未找到翻译: {name}")
                return False
    elif isinstance(item, str):
        # 处理字符串类型的配置项（如negative_prompts）
        chinese = translate_name(item)
        if chinese:
            return {'name': item, 'chinese': chinese}
        else:
            print(f"未找到翻译(字符串): {item}")
            return None
    
    return False

def process_config(config):
    """
    递归处理配置文件
    """
    modified = False
    
    if isinstance(config, dict):
        for key, value in config.items():
            if isinstance(value, list):
                new_list = []
                for item in value:
                    result = process_item(item)
                    if result is True:
                        modified = True
                        new_list.append(item)
                    elif isinstance(result, dict):
                        modified = True
                        new_list.append(result)
                    else:
                        new_list.append(item)
                config[key] = new_list
            elif isinstance(value, dict):
                if process_config(value):
                    modified = True
    
    return modified

def main():
    """
    主函数
    """
    # 读取配置文件
    config_path = Path(__file__).parent / 'prompts_config.json'
    
    print("正在读取配置文件...")
    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)
    
    print("正在处理配置文件...")
    modified = process_config(config)
    
    if modified:
        print("正在保存配置文件...")
        # 备份原文件
        backup_path = config_path.with_suffix('.json.backup')
        with open(backup_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, ensure_ascii=False, indent=2)
        print(f"已创建备份文件: {backup_path}")
        
        # 保存修改后的文件
        with open(config_path, 'w', encoding='utf-8') as f:
            json.dump(config, f, ensure_ascii=False, indent=2)
        print("配置文件已更新!")
    else:
        print("没有需要更新的内容")

if __name__ == '__main__':
    main()
